server {
    listen 443 ssl;
    server_name _;

    ssl_certificate     /etc/nginx/certs/fullchain.pem;
    ssl_certificate_key /etc/nginx/certs/privkey.pem;

    root /usr/share/nginx/html;
    index index.html;

    # mantém a porta 4545 no redirect do swagger
    location = /api/docs {
        return 302 https://$http_host/api/docs/;
    }

    # compatibilidade com bundles antigos que ainda chamem /api/api/*
    location ^~ /api/api/ {
        rewrite ^/api/api/(.*)$ /api/$1 break;

        proxy_pass http://api:3000;
        proxy_http_version 1.1;

        proxy_set_header Host $http_host;
        proxy_set_header X-Forwarded-Host $http_host;
        proxy_set_header X-Forwarded-Proto https;
        proxy_set_header X-Forwarded-Port 4545;

        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;

        proxy_redirect off;
    }

    # proxy normal da API
    location /api/ {
        proxy_pass http://api:3000;
        proxy_http_version 1.1;

        proxy_set_header Host $http_host;
        proxy_set_header X-Forwarded-Host $http_host;
        proxy_set_header X-Forwarded-Proto https;
        proxy_set_header X-Forwarded-Port 4545;

        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;

        proxy_redirect off;
    }

    location / {
        try_files $uri $uri/ /index.html;
    }
}
